[package]
name = "lua_parser"
version = "0.1.0"
authors = ["lgreathouse <me@lpghatguy.com>"]

[dependencies]
regex = "0.2"
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"

[dev-dependencies]
serde_json = "1.0"
